language: node_js
node_js:
    - "7"
install:
    - cd src && npm run update-terminal && npm install
script:
    - cd src && npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: src/dist
    repo: zjhou/zjhou.github.io
    keep_history: true
    target_branch: master
    on:
        branch: master
